version: "2"

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    networks:
      - nginx-net

  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    volumes:
      - /vagrant/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /vagrant/nginx/ssl/private/nginx-selfsigned.key:/etc/nginx/ssl.key:ro
      - /vagrant/nginx/ssl/private/nginx-selfsigned.crt:/etc/nginx/ssl.crt:ro
    ports:
      - "81:80"
      - "443:443"
    networks:
      - nginx-net

volumes:
  nexus-data: {}

networks:
  nginx-net:
